* vitis build script now creates separate workspace for each target design * consolidated vivado batch files * updated docs

diff --git a/Vitis/Makefile b/Vitis/Makefile
--- a/Vitis/Makefile
+++ b/Vitis/Makefile
@@ -8,8 +8,6 @@ RM = rm -rf
 ROOT_DIR = $(shell pwd)
 XSCT = $(XILINX_VITIS)/bin/xsct
 BD_NAME = rpi
-APP_POSTFIX = _app
-SYS_POSTFIX = $(APP_POSTFIX)_system
 
 # defaults
 .DEFAULT_GOAL := workspace
@@ -17,24 +15,44 @@ TARGET ?= none
 JOBS ?= 8
 
 # valid targets
-zcu104_target := 0
-zcu102_hpc0_target := 0
-zcu102_hpc1_target := 0
-zcu106_hpc0_target := 0
-pynqzu_target := 0
-genesyszu_target := 0
-uzev_target := 0
-zcu106_pcie_target := 0
+zcu104_target := zynqMP
+zcu102_hpc0_target := zynqMP
+zcu102_hpc1_target := zynqMP
+zcu106_hpc0_target := zynqMP
+pynqzu_target := zynqMP
+genesyszu_target := zynqMP
+uzev_target := zynqMP
+zcu106_pcie_target := zynqMP
 
 TARGET_LIST := $(sort $(patsubst %_target,%,$(filter %_target,$(.VARIABLES))))
 
 # Vitis paths
 VIT_SCRIPT_WS = tcl/build-vitis.tcl
+VIT_TARGET_WS = $(ROOT_DIR)/$(TARGET)_workspace
+VIT_LOCK = $(ROOT_DIR)/.$(TARGET).lock
+VIT_BOOT = $(ROOT_DIR)/boot
+VIT_BOOT_TARG = $(VIT_BOOT)/$(TARGET)
 
 # Vivado paths
 VIV_DIR = $(ROOT_DIR)/../Vivado
 VIV_PRJ_DIR = $(VIV_DIR)/$(TARGET)
 VIV_XSA = $(VIV_PRJ_DIR)/$(BD_NAME)_wrapper.xsa
+
+# These macros return values from the valid target lists defined above
+define get_template_name
+$(word 1,$($(1)_target))
+endef
+
+# The name of the boot image of the baremetal app depends on the device
+ifeq ($(call get_template_name,$(TARGET)), microblaze)
+	VIT_BOOT_FILE = $(VIT_BOOT_TARG)/$(TARGET).bit
+else ifeq ($(call get_template_name,$(TARGET)), zynq)
+	VIT_BOOT_FILE = $(VIT_BOOT_TARG)/BOOT.BIN
+else ifeq ($(call get_template_name,$(TARGET)), zynqMP)
+	VIT_BOOT_FILE = $(VIT_BOOT_TARG)/BOOT.BIN
+else ifeq ($(call get_template_name,$(TARGET)), versal)
+	VIT_BOOT_FILE = $(VIT_BOOT_TARG)/BOOT.BIN
+endif
 
 .PHONY: help
 help:
@@ -46,8 +64,11 @@ help:
 	@echo '  make all JOBS=<val>'
 	@echo '    Create the Vitis workspace and add applications for all targets.'
 	@echo ''
-	@echo '  make clean'
-	@echo '    Delete the Vitis workspace and all applications.'
+	@echo '  make clean TARGET=<target>'
+	@echo '    Delete the Vitis workspace and all applications for specified target.'
+	@echo ''
+	@echo '  make clean_all'
+	@echo '    Delete all Vitis workspaces and all applications.'
 	@echo ''
 	@echo 'Parameters:'
 	@echo ''
@@ -62,23 +83,43 @@ help:
 
 .PHONY: all
 all:
+	@{ \
 	for targ in $(TARGET_LIST); do \
-		$(MAKE) workspace TARGET=$$targ; \
-	done
+		$(MAKE) --no-print-directory workspace TARGET=$$targ; \
+	done; \
+	}
 
 .PHONY: workspace
-workspace: check_target $(VIV_XSA)
+workspace: check_target
+	@if [ -f $(VIT_LOCK) ]; then \
+		echo "$(TARGET) is locked. Skipping..."; \
+	else \
+		touch $(VIT_LOCK); \
+		$(MAKE) workspace_locked TARGET=$(TARGET) JOBS=$(JOBS); \
+		rm -f $(VIT_LOCK); \
+	fi
+
+workspace_locked: $(VIT_TARGET_WS) $(VIT_BOOT_FILE)
+
+$(VIT_TARGET_WS) $(VIT_BOOT_FILE): $(VIV_XSA)
+	@if [ -d $@ ]; then echo "Workspace for $(TARGET) already exists but is outdated. Use 'make clean TARGET=$(TARGET)' to remove it."; exit 1; fi
 	$(XSCT) $(VIT_SCRIPT_WS) $(TARGET)
 
 $(VIV_XSA):
 	$(MAKE) -C $(VIV_DIR) xsa TARGET=$(TARGET) JOBS=$(JOBS)
 
 .PHONY: clean
-clean:
+clean: check_target
+	$(RM) $(TARGET)_workspace
+
+.PHONY: clean_all
+clean_all:
+	@{ \
 	for targ in $(TARGET_LIST); do \
-		$(RM) $${targ} $${targ}$(APP_POSTFIX) $${targ}$(SYS_POSTFIX); \
-	done
-	$(RM) boot .metadata .Xil IDE.log .analytics updatemem*.jou updatemem*.log RemoteSystemsTempFiles embeddedsw
+		$(RM) $${targ}_workspace; \
+	done; \
+	$(RM) boot .Xil RemoteSystemsTempFiles; \
+	}
 
 check_target:
 ifndef $(TARGET)_target
